name = "Brevity"
license = "MIT"
licenselink = "https://github.com/eweix/brevity/blob/master/LICENSE"
description = "Minimal Hugo theme."
homepage = "https://github.com/eweix/brevity/"
tags = ["blog", "plain", "blank", "starter", "development"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "eweix"
  homepage = "https://github.com/eweix"
