name = "Eloquence"
license = "MIT"
licenselink = "https://github.com/eweix/eloquence/blob/master/LICENSE"
description = "Fast Hugo theme with sidebar."
homepage = "https://github.com/eweix/eloquence/"
tags = ["blog", "plain", "sidebar", "professional", "development"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "eweix"
  homepage = "https://github.com/eweix"
